"""
Godot Animator — AI Dev assembles animations directly in Godot.

Uses Godot MCP tools to:
  1. Create SpriteFrames resources with animation tracks
  2. Configure AnimationPlayer with proper timings
  3. Attach GPUParticles2D nodes for magic/spell effects
  4. Add shader effects (outline glow, hit flash) for polish
  5. Wire up signals (animation_finished → state machine transitions)

AI Dev learns to build a complete Godot animation pipeline from scratch.
"""
from __future__ import annotations
import json
import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ── GDScript templates AI Dev can write and attach to nodes ───────────────────

SPRITE_CONTROLLER_TEMPLATE = '''extends AnimatedSprite2D

## Auto-generated by AI Dev — Isekai Chronicles Animation System
## Handles sprite animation state with smooth transitions and effects.

signal animation_changed(anim_name: String)

@export var idle_anim    : String = "idle"
@export var walk_anim    : String = "walk"
@export var run_anim     : String = "run"
@export var attack_anim  : String = "attack"
@export var cast_anim    : String = "cast"
@export var hit_anim     : String = "hit"
@export var death_anim   : String = "death"

var _current_state : String = "idle"
var _is_dead       : bool   = false
var _facing_right  : bool   = true

@onready var _particles_hit  : GPUParticles2D = $HitParticles   if has_node("HitParticles")  else null
@onready var _particles_cast : GPUParticles2D = $CastParticles  if has_node("CastParticles") else null


func _ready() -> void:
	play(idle_anim)
	animation_finished.connect(_on_animation_finished)


func set_state(state: String) -> void:
	if _is_dead or state == _current_state:
		return
	_current_state = state
	match state:
		"idle":   play(idle_anim)
		"walk":   play(walk_anim)
		"run":    play(run_anim)
		"attack": _play_once(attack_anim)
		"cast":
			_play_once(cast_anim)
			if _particles_cast:
				_particles_cast.restart()
		"hit":
			_play_once(hit_anim)
			if _particles_hit:
				_particles_hit.restart()
			_flash_white()
		"death":
			_is_dead = true
			_play_once(death_anim)
	animation_changed.emit(state)


func face_direction(direction: Vector2) -> void:
	if direction.x != 0:
		_facing_right = direction.x > 0
		scale.x = 1.0 if _facing_right else -1.0


func _play_once(anim: String) -> void:
	if sprite_frames and sprite_frames.has_animation(anim):
		play(anim)


func _on_animation_finished() -> void:
	if _current_state in ["attack", "cast", "hit"]:
		set_state("idle")
	elif _current_state == "death":
		stop()


func _flash_white() -> void:
	modulate = Color.WHITE * 2.0
	var tween := create_tween()
	tween.tween_property(self, "modulate", Color.WHITE, 0.15)
'''

PARTICLE_EFFECT_TEMPLATE = '''extends GPUParticles2D

## Auto-generated by AI Dev — {effect_name} effect
## Attach to character node for {effect_type} visual feedback.

func _ready() -> void:
	emitting = false
	one_shot  = true


func play_effect() -> void:
	restart()
'''

HIT_SHADER = """shader_type canvas_item;

uniform float flash_amount : hint_range(0.0, 1.0) = 0.0;
uniform vec4  flash_color  : source_color = vec4(1.0, 1.0, 1.0, 1.0);

void fragment() {
	vec4 tex = texture(TEXTURE, UV);
	COLOR = mix(tex, vec4(flash_color.rgb, tex.a), flash_amount * tex.a);
}
"""

OUTLINE_SHADER = """shader_type canvas_item;

uniform float outline_width : hint_range(0.0, 4.0) = 1.0;
uniform vec4  outline_color : source_color = vec4(0.0, 0.0, 0.0, 1.0);

void fragment() {
	vec4 tex = texture(TEXTURE, UV);
	vec2 px  = outline_width / vec2(textureSize(TEXTURE, 0));
	float a  = texture(TEXTURE, UV + vec2( px.x, 0.0)).a
	          + texture(TEXTURE, UV + vec2(-px.x, 0.0)).a
	          + texture(TEXTURE, UV + vec2(0.0,  px.y)).a
	          + texture(TEXTURE, UV + vec2(0.0, -px.y)).a;
	COLOR = mix(vec4(outline_color.rgb, min(a, 1.0)), tex, tex.a);
}
"""


class GodotAnimator:
    """
    AI Dev's Godot animation assembly system.
    Writes GDScript files and returns setup instructions for Godot MCP.
    """

    def __init__(self, project_path: str = ""):
        self.project_path = project_path or os.getcwd()

    def build_animated_sprite(
        self,
        character_name: str,
        animation_frames: Dict[str, List[Path]],
        fps: int = 8,
        output_dir: str = "godot_ai_colony/assets/characters",
    ) -> Dict:
        """
        Prepare all files needed to set up an AnimatedSprite2D in Godot.

        animation_frames: {"walk": [frame0.png, frame1.png, ...], "attack": [...], ...}

        Returns a dict of instructions + file paths for Godot MCP to use.
        """
        clean_name = character_name.lower().replace(" ", "_")
        asset_dir = Path(self.project_path) / output_dir / clean_name
        asset_dir.mkdir(parents=True, exist_ok=True)

        # Copy frames into project asset dir
        frame_info: Dict[str, List[str]] = {}
        for anim_name, frame_paths in animation_frames.items():
            frame_info[anim_name] = []
            for i, src_path in enumerate(frame_paths):
                src_path = Path(src_path)
                if src_path.exists():
                    dst = asset_dir / f"{anim_name}_{i:02d}.png"
                    dst.write_bytes(src_path.read_bytes())
                    frame_info[anim_name].append(str(dst.relative_to(self.project_path)))

        # Write the sprite controller script
        script_path = asset_dir / f"{clean_name}_sprite.gd"
        script_path.write_text(SPRITE_CONTROLLER_TEMPLATE)

        # Write shaders
        shaders_dir = Path(self.project_path) / "godot_ai_colony/shaders"
        shaders_dir.mkdir(parents=True, exist_ok=True)
        (shaders_dir / "hit_flash.gdshader").write_text(HIT_SHADER)
        (shaders_dir / "outline.gdshader").write_text(OUTLINE_SHADER)

        # Return Godot MCP setup instructions
        return {
            "character_name": clean_name,
            "asset_dir": str(asset_dir.relative_to(self.project_path)),
            "script_path": str(script_path.relative_to(self.project_path)),
            "frame_info": frame_info,
            "fps": fps,
            "godot_setup": self._generate_setup_instructions(clean_name, frame_info, fps),
        }

    def _generate_setup_instructions(
        self, name: str, frame_info: Dict[str, List[str]], fps: int
    ) -> List[Dict]:
        """Return ordered list of Godot MCP operations to set up the animation."""
        instructions = []

        # 1. Create AnimatedSprite2D node
        instructions.append({
            "op": "add_node",
            "type": "AnimatedSprite2D",
            "name": f"{name}_sprite",
            "parent": "root",
        })

        # 2. Create SpriteFrames and add animations
        for anim_name, frames in frame_info.items():
            instructions.append({
                "op": "add_animation",
                "node": f"{name}_sprite",
                "animation": anim_name,
                "fps": fps,
                "frames": frames,
                "loop": anim_name in ("idle", "walk", "run"),
            })

        # 3. Attach controller script
        instructions.append({
            "op": "attach_script",
            "node": f"{name}_sprite",
            "script": f"godot_ai_colony/assets/characters/{name}/{name}_sprite.gd",
        })

        # 4. Add hit particle effect node
        instructions.append({
            "op": "add_node",
            "type": "GPUParticles2D",
            "name": "HitParticles",
            "parent": f"{name}_sprite",
            "properties": {
                "amount": 20,
                "emitting": False,
                "one_shot": True,
                "lifetime": 0.4,
            },
        })

        # 5. Add cast/spell particle effect node
        instructions.append({
            "op": "add_node",
            "type": "GPUParticles2D",
            "name": "CastParticles",
            "parent": f"{name}_sprite",
            "properties": {
                "amount": 40,
                "emitting": False,
                "one_shot": True,
                "lifetime": 0.8,
            },
        })

        # 6. Apply hit flash shader
        instructions.append({
            "op": "apply_shader",
            "node": f"{name}_sprite",
            "shader": "godot_ai_colony/shaders/hit_flash.gdshader",
        })

        return instructions

    def write_particle_scripts(self, output_dir: str = "godot_ai_colony/assets/effects") -> List[str]:
        """Write re-usable particle effect scripts for magic/hit effects."""
        effects = [
            ("hit_spark", "hit impact"),
            ("cast_glow", "magic cast"),
            ("death_burst", "death explosion"),
            ("level_up_sparkle", "level up celebration"),
        ]
        out_dir = Path(self.project_path) / output_dir
        out_dir.mkdir(parents=True, exist_ok=True)
        written = []
        for name, desc in effects:
            content = PARTICLE_EFFECT_TEMPLATE.format(effect_name=name, effect_type=desc)
            path = out_dir / f"{name}.gd"
            path.write_text(content)
            written.append(str(path.relative_to(self.project_path)))
        return written

    def generate_animation_player_track(
        self,
        animations: List[str],
        node_path: str,
        fps: int = 8,
    ) -> str:
        """
        Generate GDScript to programmatically build an AnimationPlayer with all tracks.
        Useful when SpriteFrames approach is insufficient.
        """
        lines = [
            "## Auto-generated AnimationPlayer setup by AI Dev",
            "func _setup_animation_player(player: AnimationPlayer) -> void:",
        ]
        for anim in animations:
            lines += [
                f"\tvar {anim}_anim := Animation.new()",
                f"\t{anim}_anim.length = 1.0 / {fps} * 8  # 8 frames at {fps}fps",
                f"\t{anim}_anim.loop_mode = Animation.LOOP_LINEAR if '{anim}' in ['idle','walk','run'] else Animation.LOOP_NONE",
                f"\tplayer.add_animation_library('', AnimationLibrary.new())",
                f"\tplayer.get_animation_library('').add_animation('{anim}', {anim}_anim)",
                "",
            ]
        return "\n".join(lines)
